{%set name = "refnx" %}
{%set version = "0.0.9" %}
{%set sha256 = "cfbf29fc3820f206a6b1412a46838c8107f9b9d1a5f985e6485d9633e5c1c41d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/refnx/refnx/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - numpy x.x
    - cython
    - setuptools

  run:
    - python
    - numpy x.x
    - scipy
    - xlrd
    - pandas
    - lmfit
    - emcee
    - uncertainties
    - numdifftools
    - h5py
    - six

test:
  requires:
    - nose

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Neutron and X-ray Reflectometry Analysis'
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
