{% set name = "refnx" %}
{% set version = "0.1.1" %}
{% set sha256 = "f4dbe5642d1bc3298c9f4a3040b35df217a685206dc48067c00086f598b898d9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/refnx/refnx/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - setuptools

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - xlrd
    - pandas
    - uncertainties
    - h5py
    - matplotlib
    - ipywidgets
    - traitlets
    - six
    - corner
    - tqdm

test:
  requires:
    - pytest
  commands:
    - py.test --pyargs refnx -v --duration=0

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Neutron and X-ray Reflectometry Analysis'
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
