{%set name = "refnx" %}
{%set version = "0.0.14" %}
{%set sha256 = "c7f8cc0221a2fa955b6a318d66d34cbdee03d958492808d9971931421be67b8b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/refnx/refnx/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - numpy 1.11.*
    - cython
    - setuptools

  run:
    - python
    - numpy >=1.11
    - scipy
    - xlrd
    - pandas
    - uncertainties
    - h5py
    - matplotlib
    - ipywidgets
    - traitlets
    - IPython
    - six

test:
  requires:
    - pytest
  commands:
    - py.test --pyargs refnx -v --duration=0

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Neutron and X-ray Reflectometry Analysis'
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
