{% set name = "refnx" %}
{% set version = "0.1.16" %}
{% set sha256 = "b43e72fde7f72580243ed3db533e110d49125b6f1ba3f555e550a7d9e6c32594" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/refnx/refnx/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - llvm-openmp  # [osx]

  host:
    - python
    - numpy
    - cython
    - setuptools
    - xorg-libxfixes  # [linux]
    - llvm-openmp  # [osx]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - llvm-openmp  # [osx]

test:
  requires:
    - pytest
    - pytest-qt
    # - uncertainties
    - scipy>=1.2.0
    # - xlrd
    # - pandas
    # - h5py
    - matplotlib
    - ipywidgets
    - traitlets
    - corner
    - tqdm
    # try using pyqt from defaults instead of conda-forge
    - pyqt >=5
    - periodictable

  commands:
    - export MPLBACKEND=agg  # [osx and linux]
    # - py.test --pyargs refnx -v --durations=0  # [osx and win]
    # can't get the pyqt GUI test to run for some reason, not even with xvfb
    ## - xvfb-run -a bash -c 'py.test --pyargs refnx -v --duration=0'  # [linux]
    # - conda install -y -c defaults pyqt; xvfb-run -w 3 -d bash -c 'py.test --pyargs refnx -v --durations=0'  # [linux]

    # 0.1.16 detail individual tests to avoid use of packages that have conda-forge conflicts.
    # don't bother to test reduction code. This is already comprehensively tested.
    - pytest --pyargs refnx.analysis --pyargs refnx.dataset --pyargs refnx._lib --pyargs refnx.util
    - pytest --pyargs refnx.reflect  # [osx and win]
    - xvfb-run -w 3 -d bash -c 'pytest --pyargs refnx.reflect'  # [linux]

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Neutron and X-ray Reflectometry Analysis
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
