{%set name = "refnx" %}
{%set version = "0.0.12" %}
{%set sha256 = "48a7878921c220580ff383f57087bd2009c69c718fcd0ca4871f4547095fddbb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/refnx/refnx/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - numpy
    - cython
    - setuptools

  run:
    - python
    - numpy x.x
    - scipy
    - xlrd
    - pandas
    - lmfit
    - emcee
    - uncertainties
    - h5py

test:
  requires:
    - pytest

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Neutron and X-ray Reflectometry Analysis'
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
