{% set name = "refnx" %}
{% set version = "0.1.62" %}
{% set sha256 = "0f9bbb7af14b2a0a585ef77ceaecd07dee45cd3d7f18e5b805fc61812ac19a65" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: refnx-{{ version }}.zip
  url: https://github.com/refnx/refnx/archive/refs/tags/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0

  skip: true  # [py<311]


{% set numpy = "2.0.0" %}


requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - numpy >={{ numpy }}                 # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - ninja

  host:
    - python
    - numpy >={{ numpy }}
    - cython
    - meson-python
    - pip
    - python-build
    - llvm-openmp  # [osx]

  run:
    - python
    - scipy
    - llvm-openmp  # [osx]

test:
  requires:
    - pytest
    - pytest-qt  # [osx and win]
    # - uncertainties
    - scipy >=1.2.0
    # - xlrd
    # - pandas
    # - h5py
    - matplotlib
    - ipywidgets
    - traitlets
    - corner
    - tqdm
    - attrs
    - qtpy
    - pyside6
    - periodictable

  commands:
    - python -c "import refnx;refnx.test(tests=['refnx.reflect.tests.test_reflect'])"

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Neutron and X-ray Reflectometry Analysis
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
