{% set name = "refnx" %}
{% set version = "0.1.61" %}
{% set sha256 = "c81005a2db2b91100cd4d9a6bf3f6e382b5714181a338c58bcdd08334993c74a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: refnx-{{ version }}.zip
  url: https://github.com/refnx/refnx/archive/refs/tags/v{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    - 0001-cross-compile.patch

build:
  number: 2

  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]

  host:
    - python
    - numpy
    - cython
    - setuptools
    - llvm-openmp  # [osx]

  run:
    - python
    - scipy
    - llvm-openmp  # [osx]

test:
  requires:
    - pytest
    - pytest-qt  # [osx and win]
    # - uncertainties
    - scipy >=1.2.0
    # - xlrd
    # - pandas
    # - h5py
    - matplotlib
    - ipywidgets
    - traitlets
    - corner
    - tqdm
    - attrs
    - qtpy
    - pyside6
    - periodictable

  commands:
    - pytest --pyargs refnx.reflect.tests.test_reflect --pyargs refnx.analysis

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Neutron and X-ray Reflectometry Analysis
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
