{% set name = "refnx" %}
{% set version = "0.1.50" %}
{% set sha256 = "0b96405f819473051cc8e2d5bca8c87a402a20bfdbe833f01a8450d1efe44161" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: refnx-{{ version }}.zip
  url: https://github.com/refnx/refnx/archive/refs/tags/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1

  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - llvm-openmp  # [osx]

  host:
    - python
    - numpy
    - cython
    - setuptools
    - xorg-libxfixes  # [linux]
    - llvm-openmp  # [osx]

  run:
    - python
    - scipy
    - llvm-openmp  # [osx]

test:
  requires:
    - pytest
    - pytest-qt  # [osx and win]
    # - uncertainties
    - scipy>=1.2.0
    # - xlrd
    # - pandas
    # - h5py
    - matplotlib
    - ipywidgets
    - traitlets
    - corner
    - tqdm
    - attrs
    - qtpy
    - pyside6
    - periodictable

  commands:
    - export MPLBACKEND=agg  # [osx and linux]
    # - py.test --pyargs refnx -v --durations=0  # [osx and win]
    # can't get the pyqt GUI test to run for some reason, not even with xvfb
    ## - xvfb-run -a bash -c 'py.test --pyargs refnx -v --duration=0'  # [linux]
    # - conda install -y -c defaults pyqt; xvfb-run -w 3 -d bash -c 'py.test --pyargs refnx -v --durations=0'  # [linux]

    # 0.1.16 detail individual tests to avoid use of packages that have conda-forge conflicts.
    # don't bother to test reduction code. This is already comprehensively tested.
    # - pytest --pyargs refnx.analysis --pyargs refnx.dataset --pyargs refnx._lib --pyargs refnx.util  # [not py==38]
    # - pytest --pyargs refnx.reflect  # [osx and win]
    # - xvfb-run -w 3 -d bash -c 'pytest --pyargs refnx.reflect.test'  # [linux]

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Neutron and X-ray Reflectometry Analysis
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
